name: Pytest CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libjack-dev
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Setup virtual environment
        run: |
          uv venv
      - name: Install dependencies
        run: |
          uv pip install --upgrade pip
          uv pip install -e ".[dev]"
      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pytest