name: Ruff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libjack-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Setup virtual environment
        run: |
          uv venv

      - name: Install dependencies
        run: |
          uv pip install --upgrade pip
          uv pip install -e ".[dev]"
          pip install ruff==0.9.1

      - name: Run Ruff Check
        run: ruff check --line-length=127

      - name: Run Ruff Format Check
        run: ruff format --check --diff --line-length=127